### ISSUE TITLE
Missing Breach, Cypher, Raze

### ISSUE THREAD

**Issue by robb1ssell** [Blunix9/valorant-icons#1]
Hey! Nice work on the icons. Really appreciate you taking the effort.

I assume you know these are missing? Have an eta on them?

**Comment by Blunix9** [comment]
Hi! Yes, I know about it. I'll add them soon.

**Comment by robb1ssell** [comment]
I figured, thanks for doing them.

What are you using for the source?

**Comment by Blunix9** [comment]
I'm taking a screenshot in the game.

**Comment by Blunix9** [comment]
I've added missing icons.
